// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    partial class MovieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.MovieEntry", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Fantasy",
                            DirectorFirstName = "Marbalble",
                            DirectorLastName = "Nonito",
                            Edited = false,
                            LentTo = "Josh",
                            Notes = "This is a great movie!",
                            Rating = "PG",
                            Title = "Encanto",
                            Year = "2022"
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action",
                            DirectorFirstName = "Stephen",
                            DirectorLastName = "Spielberg",
                            Edited = false,
                            LentTo = "Britti",
                            Notes = "MY FAVORITE",
                            Rating = "PG",
                            Title = "The Count of Monte Cristo",
                            Year = "1986"
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Drama",
                            DirectorFirstName = "Johnny",
                            DirectorLastName = "Appleseed",
                            Edited = false,
                            LentTo = "Jonah",
                            Notes = "Don't cry.",
                            Rating = "PG-13",
                            Title = "Titanic",
                            Year = "1990"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
